#!/usr/bin/env bash

current_branch="$(git rev-parse --abbrev-ref HEAD)"
git checkout master
git checkout -B dist
make HTML_INJECT_FLAGS="-CDN" release
git add -f dist
git commit -m "Add current master build"
git push -f origin dist
git checkout "${current_branch}"
mkdir -p "dist/js"
mkdir -p "dist/css"
make clean
make
