#!/usr/bin/env bash

current_branch="$(git rev-parse --abbrev-ref HEAD)"
git checkout master
git branch -D gh-pages
git checkout --orphan gh-pages
git reset
make HTML_INJECT_FLAGS="-CDN" release
git add -f dist
git commit --author "update-gh-pages <auto@build.local>" -m "Add current master build"
git push -f origin gh-pages
git checkout -f "${current_branch}"
make dist-setup
make clean
make targets

